# Generated by Django 4.0.5 on 2022-06-07 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('idFoto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreFoto', models.CharField(max_length=100)),
                ('nombreArchivo', models.CharField(max_length=256)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('imagenProducto', models.CharField(max_length=150, verbose_name='Imagen del Producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio del Producto')),
                ('stockProducto', models.IntegerField(verbose_name='Stock del Producto')),
                ('categoriaProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.categoria')),
            ],
        ),
    ]
