# Generated by Django 4.0.5 on 2022-06-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('idContacto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreContacto', models.CharField(max_length=200)),
                ('imagenContacto', models.CharField(max_length=150)),
            ],
        ),
    ]
