# Generated by Django 4.0.5 on 2022-07-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoriaProducto',
        ),
    ]
